# Generated by Django 4.2.7 on 2025-04-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customshipping',
            old_name='shippingReceipts',
            new_name='ShippingOrder',
        ),
        migrations.RenameField(
            model_name='parselshipping',
            old_name='shippingReceipts',
            new_name='ShippingOrder',
        ),
    ]
