# Generated by Django 4.2.7 on 2024-02-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='location_type',
            field=models.CharField(choices=[('WAREHOSUE', 'warehosue'), ('RETAIL', 'retail'), ('DISTRIBUTION_CENTER', 'distributionCENTER')], default='retail', max_length=50),
        ),
    ]
