# Generated by Django 4.2.7 on 2025-04-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_shippingreceipts_customshipping_shippingorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptline',
            old_name='salesReceipt',
            new_name='order',
        ),
    ]
