# Generated by Django 4.2.7 on 2025-03-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_salesreceipt_status_shipping_parselshipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashPaymentmethod', to='api.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creaditcardPaymentmethod', to='api.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='receiptline',
            name='salesReceipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesReceiptLines', to='api.salesreceipt'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='ShippintReceipts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ShippingReceipts', to='api.salesreceipt'),
        ),
        migrations.AlterField(
            model_name='transferpayment',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferPaymentmethod', to='api.paymentmethod'),
        ),
    ]
