# Generated by Django 4.2.7 on 2024-07-28 16:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='varient',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='product',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1000, 1500], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='varient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
