# Generated by Django 4.2.7 on 2024-04-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
