# Generated by Django 4.2.7 on 2024-04-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_locations_phone_alter_locations_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='store_number',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
