# Generated by Django 4.2.7 on 2025-03-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cashpayment_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptline',
            name='salesReceipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceiptLines', to='api.salesreceipt'),
        ),
    ]
