# Generated by Django 4.2.7 on 2024-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_create_on_product_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='min_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
