# Generated by Django 4.2.7 on 2025-03-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_receiptline_salesreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashPaymentMethod', to='api.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creaditcardPaymentMethod', to='api.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transferpayment',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferPaymentMethod', to='api.paymentmethod'),
        ),
    ]
