# Generated by Django 4.2.7 on 2024-07-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_varient_min_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
