# Generated by Django 4.2.7 on 2025-07-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customer_phone_customer_blacklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshipping',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Procesando'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('RETURN', 'Devolucion'), ('CANCELED', 'Cancelado')], default='procesando', max_length=25),
        ),
        migrations.AlterField(
            model_name='parselshipping',
            name='status',
            field=models.CharField(blank=True, choices=[('PROCESSING', 'Procesando'), ('SHIPPED', 'Enviado'), ('PICKEDUP', 'Recojido'), ('NOSHOW', 'No Retiro'), ('RETURN', 'Devolucion'), ('CANCELED', 'Cancelado')], default='procesando', max_length=25, null=True),
        ),
    ]
