# Generated by Django 4.2.7 on 2024-07-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_varient_low_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='low_stock',
        ),
        migrations.RemoveField(
            model_name='varient',
            name='tags',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='varients', to='api.tags'),
        ),
    ]
