# Generated by Django 4.2.7 on 2025-03-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_creditcardpayment_paymentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreceipt',
            name='PaymentMethod',
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='paymentMethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentMethods', to='api.paymentmethod'),
            preserve_default=False,
        ),
    ]
