# Generated by Django 4.2.7 on 2025-07-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customshipping_address_customshipping_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customshipping',
            old_name='extraDetails',
            new_name='addressLineTwo',
        ),
        migrations.RenameField(
            model_name='customshipping',
            old_name='zip_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='customshipping',
            old_name='ShippingOrder',
            new_name='shippingOrder',
        ),
        migrations.RenameField(
            model_name='customshipping',
            old_name='address',
            new_name='streetAddress',
        ),
        migrations.RenameField(
            model_name='parselshipping',
            old_name='extraDetails',
            new_name='addressLineTwo',
        ),
        migrations.RenameField(
            model_name='parselshipping',
            old_name='zip_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='parselshipping',
            old_name='ShippingOrder',
            new_name='shippingOrder',
        ),
        migrations.RenameField(
            model_name='parselshipping',
            old_name='address',
            new_name='streetAddress',
        ),
    ]
