# Generated by Django 4.2.7 on 2025-03-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_salesreceipt_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentType', to='api.paymentmethod'),
        ),
    ]
