# Generated by Django 4.2.7 on 2025-07-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_extradetails_customshipping_addresslinetwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customshipping',
            name='countryCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customshipping',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customshipping',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customshipping',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='countryCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Avierto'), ('CLOSED', 'Cerrado'), ('PAID', 'Pagado'), ('PROCESSING', 'procesando'), ('CANCELED', 'Cancelado'), ('RETURN', 'Retorno')], default='Avierto', max_length=25, null=True),
        ),
    ]
