# Generated by Django 4.2.7 on 2025-03-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cashpayment_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='paymentMethod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashPaymentMethod', to='api.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='paymentMethod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditcardPaymentMethod', to='api.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transferpayment',
            name='paymentMethod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferPaymentMethod', to='api.paymentmethod'),
        ),
    ]
