# Generated by Django 4.2.7 on 2025-03-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cashpayment_id_remove_creditcardpayment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptline',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
