# Generated by Django 4.2.7 on 2025-08-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Procesando'), ('PAID', 'Pagado'), ('CLOSED', 'Cerrado'), ('RETURN', 'Devolucion'), ('CANCELED', 'Cancelado')], default='Procesando', max_length=25),
        ),
    ]
