# Generated by Django 4.2.7 on 2025-03-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_receiptline_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customshipping',
            old_name='name',
            new_name='companyName',
        ),
        migrations.RenameField(
            model_name='parselshipping',
            old_name='name',
            new_name='companyName',
        ),
        migrations.RemoveField(
            model_name='customshipping',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='parselshipping',
            name='shipping',
        ),
        migrations.AddField(
            model_name='customshipping',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customshipping',
            name='shippintReceipts',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.salesreceipt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customshipping',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='shippintReceipts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.salesreceipt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customshipping',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customshipping',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customshipping',
            name='status',
            field=models.CharField(choices=[('PREPAIDED', 'Pagado'), ('PROCESSING', 'procesando'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELED', 'Cancelado')], default='procesando', max_length=25),
        ),
        migrations.AlterField(
            model_name='parselshipping',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parselshipping',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
