# Generated by Django 4.2.7 on 2025-08-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshipping',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Procesando'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('RETURN', 'Devolucion'), ('CANCELED', 'Cancelado')], default='PROCESSING', max_length=25),
        ),
    ]
