# Generated by Django 4.2.7 on 2025-03-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_name_customshipping_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customshipping',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='customshipping',
            name='shippingType',
            field=models.CharField(choices=[('PersonaShipping', 'Envio Personalizado'), ('parsel', 'Encomienda')], default='parsel', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='parselshipping',
            name='shippingType',
            field=models.CharField(choices=[('PersonaShipping', 'Envio Personalizado'), ('parsel', 'Encomienda')], default='parsel', max_length=25),
            preserve_default=False,
        ),
    ]
