# Generated by Django 4.2.7 on 2025-03-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customshipping_location_customshipping_shippingtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='neighborhood',
            new_name='extraDetails',
        ),
        migrations.AddField(
            model_name='customer',
            name='countryCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customshipping',
            name='attempts',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='parselshipping',
            name='attempts',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
