# Generated by Django 4.2.7 on 2025-08-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_banktransferpayment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btPayment', to='api.order'),
        ),
        migrations.AlterField(
            model_name='cashpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashPayment', to='api.order'),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccPayment', to='api.order'),
        ),
    ]
