# Generated by Django 4.2.7 on 2025-03-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_comment_customshipping_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customshipping',
            old_name='shippintReceipts',
            new_name='shippingReceipts',
        ),
        migrations.RenameField(
            model_name='parselshipping',
            old_name='shippintReceipts',
            new_name='shippingReceipts',
        ),
    ]
