# Generated by Django 4.2.7 on 2025-03-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_shippintreceipts_customshipping_shippingreceipts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshipping',
            name='status',
            field=models.CharField(choices=[('PREPAIDED', 'Pagado'), ('PROCESSING', 'procesando'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('RETURN', 'DEVOLUCION'), ('CANCELED', 'Cancelado')], default='procesando', max_length=25),
        ),
        migrations.AlterField(
            model_name='parselshipping',
            name='status',
            field=models.CharField(blank=True, choices=[('PREPAIDED', 'Pagado'), ('PROCESSING', 'procesando'), ('SHIPPED', 'Enviado'), ('PICKEDUP', 'Recojido'), ('NOSHOW', 'No Retiro'), ('RETURN', 'DEVOLUCION'), ('CANCELED', 'Cancelado')], default='procesando', max_length=25, null=True),
        ),
    ]
