# Generated by Django 4.2.7 on 2025-08-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_banktransferpayment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parselshipping',
            name='status',
            field=models.CharField(blank=True, choices=[('PROCESSING', 'Procesando'), ('SHIPPED', 'Enviado'), ('PICKEDUP', 'Recojido'), ('NOSHOW', 'No Retiro'), ('RETURN', 'Devolucion'), ('CANCELED', 'Cancelado')], default='PROCESSING', max_length=25, null=True),
        ),
    ]
