# Generated by Django 4.2.7 on 2025-09-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_parselshipping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='variantCategory', to='api.categories'),
        ),
        migrations.AlterField(
            model_name='varient',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='variantTags', to='api.tags'),
        ),
    ]
