# Generated by Django 4.2.7 on 2025-03-17 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customshipping_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetypes',
            name='location_id',
        ),
    ]
