# Generated by Django 4.2.7 on 2025-03-19 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_expensetypes_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='approvalDate',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expenseType',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='isACHReimbursed',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='isReimbursable',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='expensetypes',
            name='created_on',
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='description',
            field=models.CharField(default='sample', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='expense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.expense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='expense_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='isACHReimbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='isReimbursable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensetypes',
            name='merchant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
    ]
