# Generated by Django 4.2.7 on 2025-03-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_expense_amount_remove_expense_approvaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customshipping',
            name='status',
            field=models.CharField(choices=[('PREPAIDED', 'Pagado'), ('PROCESSING', 'Procesando'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('RETURN', 'DEVOLUCION'), ('CANCELED', 'Cancelado')], default='procesando', max_length=25),
        ),
        migrations.AlterField(
            model_name='parselshipping',
            name='status',
            field=models.CharField(blank=True, choices=[('PREPAIDED', 'Pagado'), ('PROCESSING', 'Procesando'), ('SHIPPED', 'Enviado'), ('PICKEDUP', 'Recojido'), ('NOSHOW', 'No Retiro'), ('RETURN', 'DEVOLUCION'), ('CANCELED', 'Cancelado')], default='procesando', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('ONHOLD', 'En Espera'), ('PROCESSING', 'Procesando'), ('PAID', 'Pagado'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CANCELED', 'Cancelado')], default='Procesando', max_length=25),
        ),
    ]
