# Generated by Django 4.2.7 on 2025-03-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_purchaseorder_totalamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderlines',
            old_name='unitPrice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='purchaseorderlines',
            old_name='units',
            new_name='quantity',
        ),
    ]
