# Generated by Django 4.2.7 on 2025-03-19 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_unitprice_purchaseorderlines_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='datePaid',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
