# Generated by Django 4.2.7 on 2025-03-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_purchaseorder_datepaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderlines',
            name='locationId',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlines',
            name='statusDate',
        ),
    ]
