# Generated by Django 4.2.7 on 2025-03-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_purchaseorderlines_locationid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderlines',
            old_name='itemName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='purchaseorderlines',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
            preserve_default=False,
        ),
    ]
