# Generated by Django 4.2.7 on 2025-03-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_itemname_purchaseorderlines_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='location_id',
            new_name='location',
        ),
    ]
