# Generated by Django 4.2.7 on 2025-03-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_purchaseorder_costcenter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='locationId',
            new_name='location',
        ),
    ]
