# Generated by Django 4.2.7 on 2025-03-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_locationid_purchaseorder_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderlines',
            name='status',
        ),
        migrations.AlterField(
            model_name='purchaseorderlines',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
