# Generated by Django 4.2.7 on 2025-03-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_purchaseorderlines_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='merchant',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
