# Generated by Django 4.2.7 on 2025-03-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_purchaseorder_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='merchant',
            new_name='murchant',
        ),
    ]
