# Generated by Django 4.2.7 on 2025-03-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_merchant_purchaseorder_murchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='murchant',
            new_name='merchant',
        ),
    ]
