# Generated by Django 4.2.7 on 2025-03-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_murchant_purchaseorder_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesreceipt',
            old_name='Location',
            new_name='location',
        ),
    ]
