# Generated by Django 4.2.7 on 2025-03-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_location_salesreceipt_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipt',
            name='paymentExecution',
            field=models.CharField(blank=True, choices=[('OPEN', 'Avierto'), ('CLOSED', 'Cerrado'), ('PAID', 'Pagado'), ('PROCESSING', 'procesando'), ('CANCELED', 'Cancelado')], default='Avierto', max_length=25, null=True),
        ),
    ]
