# Generated by Django 4.2.7 on 2025-03-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_salesreceipt_paymentexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceipt',
            name='paymentExecution',
            field=models.CharField(blank=True, choices=[('POS', 'POS'), ('SHIPPING', 'SHIPPING')], default='POS', max_length=25, null=True),
        ),
    ]
