# Generated by Django 4.2.7 on 2025-03-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_salesreceipt_paymentexecution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Avierto'), ('CLOSED', 'Cerrado'), ('PAID', 'Pagado'), ('PROCESSING', 'procesando'), ('CANCELED', 'Cancelado'), ('RETURN', 'RETURNED')], default='Avierto', max_length=25, null=True),
        ),
    ]
