# Generated by Django 4.2.7 on 2025-03-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_salesreceipt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customshipping',
            name='shippingType',
            field=models.CharField(choices=[('personalShipping', 'Envio Personalizado'), ('parcel', 'Encomienda')], max_length=25),
        ),
        migrations.AlterField(
            model_name='parselshipping',
            name='shippingType',
            field=models.CharField(choices=[('personalShipping', 'Envio Personalizado'), ('parcel', 'Encomienda')], max_length=25),
        ),
    ]
