POST http://127.0.0.1:8000/api/create_user
Content-Type: application/json

{"username": "admin1234@gmail.com", "password": "password1234", "full_name": "Jennifer Hernandez", "position":"sales", "is_employee": false }